[package]
name = "ratespiel"
version = "0.1.0"
authors = ["Ashley Gessler <68016255+asges@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
